#!/usr/bin/env bash

set -e
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
trap 'echo "\"${last_command}\" command failed with exit code $?."' EXIT

echo Assembling source file...
nasm -f win64 $1.asm -o $1.obj

echo Compiling C framework...
gcc -c $2.c
gcc -o $1 $1.obj $2.o

echo Cleaning up intermediate files...
rm $1.obj $2.o

echo Done!
